import React, { useState } from 'react';
import { 
  ShieldCheck, 
  Copy, 
  Check, 
  Printer, 
  ArrowLeft, 
  FileText, 
  HelpCircle, 
  Sparkles, 
  Building2, 
  Percent, 
  IndianRupee, 
  Info,
  Award
} from 'lucide-react';
import { formatINR, formatCreditScore } from '../utils/formatters';

export default function NegotiationCard({ formData, results, onBack }) {
  const [copied, setCopied] = useState(false);

  if (!results) return null;

  const { confidence, interestRate, affordability, recommendation } = results;
  const { decision, safeMax, lenderMax } = recommendation;
  const { comfortableEmiCeiling, lenderSanctionRange, borrowerSafeRange } = affordability;

  const loanPurpose = formData.loanPurpose || 'Personal';
  const requestedAmount = Number(formData.loanAmount) || 0;

  // Key Questions for Lender
  const lenderQuestions = [
    {
      q: "What is the final all-in APR including processing, documentation, and mandatory insurance fees?",
      why: "Lenders often quote nominal interest rates (e.g. 10.5%), but hidden processing fees or bundled insurance increase the true APR to 12.5%+."
    },
    {
      q: "Is this interest rate fixed or floating? If floating, what is the underlying benchmark rate & reset frequency?",
      why: "Floating rates linked to repo rates can fluctuate over time. Knowing the reset period protects you against unexpected EMI increases."
    },
    {
      q: "What exact processing, documentation, legal valuation, or insurance charges apply upfront?",
      why: "Ensures no surprise deductions are subtracted from your disbursed loan principal."
    },
    {
      q: "What are the foreclosure and partial prepayment charges or lock-in period restrictions?",
      why: "RBI rules forbid foreclosure penalties on floating rate personal/home loans, but fixed rate or business loans may incur 2%-4% fees."
    },
    {
      q: "If the central bank increases interest rates by 0.50% to 1.00%, how will my EMI or loan tenure adjust?",
      why: "Tests how resilient your monthly budget remains under macro interest rate hikes."
    }
  ];

  if (loanPurpose === 'Business' || recommendation?.securedLoanAdvice) {
    lenderQuestions.push({
      q: "Can this expansion loan be structured as a Secured Business Loan or Loan Against Property (LAP) backed by unencumbered property assets?",
      why: "Secured LAP structures offer 10-15 year tenures and lower interest rates (9.5%-12.5%). Note: Collateral provides product access but does NOT replace monthly cash flow required for EMI servicing."
    });
  }

  // Plain text generator for Clipboard Copying
  const generateClipboardText = () => {
    return `=== BORROWER COPILOT - LENDER NEGOTIATION SUMMARY ===
Date: ${new Date().toLocaleDateString('en-IN')}

[BORROWER PROFILE & REQUEST]
• Loan Purpose: ${loanPurpose}
• Requested Amount: ${formatINR(requestedAmount)}
• Income Type: ${formData.incomeType || 'N/A'}
• Credit Score Status: ${formData.knowsCreditScore === 'Yes' ? formatCreditScore(formData.creditScore) : 'Unknown (No bureau check)'}

[AFFORDABILITY BENCHMARKS]
• Borrower-Safe Planning Limit: ${borrowerSafeRange.text} (RECOMMENDED)
• Estimated Lender Sanction Cap: ${lenderSanctionRange.text}
• Comfortable Monthly EMI Ceiling: ${formatINR(comfortableEmiCeiling)} / month
• Fair Interest Rate Band: ${interestRate.rateRange.text}
• Estimated All-In APR Cost: ~${interestRate.estimatedApr}% APR (with ${interestRate.processingFeePercent}% fee)
• Calculation Confidence: ${confidence.level}

[5 MANDATORY QUESTIONS FOR LOAN OFFICER]
1. What is the final all-in APR including processing, documentation, and insurance fees?
2. Is this interest rate fixed or floating? What is the benchmark reset frequency?
3. What exact upfront fees or insurance deductions will be taken from the disbursed principal?
4. Are there any foreclosure, pre-payment penalty fees, or lock-in restrictions?
5. How much will my monthly EMI or tenure increase if repo rates rise by 0.5% - 1.0%?

Disclaimer: This is an educational planning tool, not a lender approval, financial advice, or credit decision.
Generated by Borrower Copilot (https://borrower-copilot.app)`;
  };

  const handleCopy = () => {
    const text = generateClipboardText();
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }).catch(err => {
      console.error('Failed to copy: ', err);
    });
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="negotiation-card-container fade-in">
      {/* Top Header Controls */}
      <div className="negotiation-actions-top no-print">
        <button type="button" className="btn-secondary" onClick={onBack}>
          <ArrowLeft size={18} />
          <span>Back to Dashboard</span>
        </button>

        <div className="action-buttons-group">
          <button type="button" className="btn-secondary copy-btn" onClick={handleCopy}>
            {copied ? <Check size={18} className="text-success" /> : <Copy size={18} />}
            <span>{copied ? 'Copied to Clipboard!' : 'Copy Summary Text'}</span>
          </button>

          <button type="button" className="btn-primary print-btn" onClick={handlePrint}>
            <Printer size={18} />
            <span>Print / Save PDF</span>
          </button>
        </div>
      </div>

      {/* Main Printable Negotiation Card */}
      <div className="printable-card-wrapper">
        <div className="card-brand-header">
          <div className="brand-left">
            <div className="card-logo-icon">
              <Sparkles size={22} />
            </div>
            <div>
              <h2 className="card-brand-title">Borrower Copilot</h2>
              <p className="card-brand-sub">Lender Negotiation & Discussion Card</p>
            </div>
          </div>

          <div className="card-date-badge">
            <span className="badge-label">Generated</span>
            <strong>{new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</strong>
          </div>
        </div>

        {/* Section 1: Summary Metric Tiles */}
        <div className="negotiation-metrics-grid">
          <div className="metric-tile">
            <span className="tile-label">Loan Purpose</span>
            <div className="tile-value">{loanPurpose}</div>
            <span className="tile-sub">Requested: {formatINR(requestedAmount)}</span>
          </div>

          <div className="metric-tile tile-highlight">
            <span className="tile-label">Borrower-Safe Target</span>
            <div className="tile-value text-primary">{borrowerSafeRange.text}</div>
            <span className="tile-sub">Use for budgeting & planning</span>
          </div>

          <div className="metric-tile">
            <span className="tile-label">Lender Capacity Cap</span>
            <div className="tile-value">{lenderSanctionRange.text}</div>
            <span className="tile-sub">Max FOIR capacity estimate</span>
          </div>

          <div className="metric-tile">
            <span className="tile-label">Comfortable EMI Ceiling</span>
            <div className="tile-value">{formatINR(comfortableEmiCeiling)} <span className="text-muted">/mo</span></div>
            <span className="tile-sub">Preserves living expenses</span>
          </div>

          <div className="metric-tile">
            <span className="tile-label">Fair Interest Rate Band</span>
            <div className="tile-value">{interestRate.rateRange.text}</div>
            <span className="tile-sub">Benchmark rate for {loanPurpose}</span>
          </div>

          <div className="metric-tile">
            <span className="tile-label">Estimated All-in Annualized Cost</span>
            <div className="tile-value text-emerald">~{interestRate.estimatedApr}% / yr</div>
            <span className="tile-sub">Includes ~{interestRate.processingFeePercent}% fee</span>
          </div>
        </div>

        {/* Confidence Banner */}
        <div className="card-confidence-bar">
          <ShieldCheck size={18} className="text-primary" />
          <span>
            Calculation Confidence: <strong>{confidence.level}</strong> &bull; {confidence.why}
          </span>
        </div>

        {/* Section 2: 5 Essential Questions to Ask the Lender */}
        <div className="questions-section">
          <div className="questions-header">
            <HelpCircle size={20} className="text-primary" />
            <h3>5 Mandatory Questions to Ask Your Loan Officer</h3>
          </div>

          <div className="questions-list">
            {lenderQuestions.map((item, idx) => (
              <div key={idx} className="question-item-card">
                <div className="question-number">Q{idx + 1}</div>
                <div className="question-body">
                  <h4>{item.q}</h4>
                  <p><strong>Why ask:</strong> {item.why}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Secured Loan / LAP Strategy Callout */}
        {recommendation?.securedLoanAdvice && (
          <div className="negotiation-tips-box secured-tips-box">
            <Building2 size={20} className="tip-icon text-amber" />
            <div>
              <strong>Secured Business Loan / LAP Alternative Strategy:</strong>
              <p>
                {recommendation.securedLoanAdvice.recommendation}
              </p>
              <p style={{ marginTop: '6px', fontSize: '0.85rem', opacity: 0.9 }}>
                <strong>Important Rule:</strong> {recommendation.securedLoanAdvice.importantNuance}
              </p>
            </div>
          </div>
        )}

        {/* Negotiation Tips Callout */}
        <div className="negotiation-tips-box">
          <Award size={20} className="tip-icon" />
          <div>
            <strong>Borrower Copilot Negotiation Strategy:</strong>
            <p>
              When talking to bank representatives, do not accept the first interest rate quote. 
              Show them this card to demonstrate you know your comfortable EMI ceiling (₹{comfortableEmiCeiling.toLocaleString('en-IN')}) 
              and the competitive rate benchmark ({interestRate.rateRange.text}). Ask them to waive processing fees or match competitor rates!
            </p>
          </div>
        </div>

        {/* Footer Disclaimer */}
        <div className="card-footer-disclaimer">
          <Info size={14} />
          <span>This is an educational planning tool, not a lender approval, financial advice, or credit decision.</span>
        </div>
      </div>
    </div>
  );
}
